/* Generated By:JavaCC: Do not edit this line. Robot.java */
package uniandes.lym.robot.control;

import uniandes.lym.robot.kernel.*;
import java.awt.Point;
import java.io.*;
import java.util.Vector;
import java.util.LinkedList;
import java.util.HashMap;

@SuppressWarnings("serial")
public class Robot implements RobotConstants {


        private RobotWorldDec world;
        HashMap<String,Integer> variables = new HashMap<String,Integer>();


        void setWorld(RobotWorld w) {
                world = (RobotWorldDec) w;
        }

  final public boolean command(StringBuffer sistema) throws ParseException {
                int x= 0;
                String salida=new String();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ROBOT:
      jj_consume_token(ROBOT);
      jj_consume_token(VARS);
      jj_consume_token(WORD);
      options(salida);
      jj_consume_token(WORD);
                    try {
                                        Thread.sleep(2000);
                                    } catch (InterruptedException e) {
                                        System.err.format("IOException: %s%n", e);
                                    }

                        sistema.append(salida);
                        {if (true) return true;}
      break;
    case 0:
      jj_consume_token(0);
                         {if (true) return false;}
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void objetoPoner(String a, int x) throws ParseException {
                int f=1;
            if (a.equals("chip"))
           {
         world.putChips(x);
            }
            else {
               world.putBalloons(x);

         }
  }

  final public void objetoRecoger(String a, int x) throws ParseException {
                int f=1;
            if (a.equals("chip"))
           {
         world.pickChips(x);
            }
            else {
               world.grabBalloons(x);

         }
  }

        /**
	 *  reconoce un numero entero sin signo
	 * @return el valor entero correspondiente al valor reconocido
	 */
  final public int numero() throws ParseException, Error {
                int total=1;
    jj_consume_token(NUMERO);
                        try
                        {
                                total = Integer.parseInt(token.image);
                        }
                        catch (NumberFormatException ee)
                        {
                                // Dada la forma de NUMERO, sabemos que solo puede tener digitos
                                // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                {if (true) throw new Error("Numero demasiado grande: "+token.image+"!!");}
                        }
                        {if (true) return total;}
    throw new Error("Missing return statement in function");
  }

  final public String letter() throws ParseException {
         String s = "";
    jj_consume_token(MI);
          s = token.image;
          {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final public String num() throws ParseException {
         String s = "";
    jj_consume_token(NUMERO);
          s = token.image;
          {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  final public String word() throws ParseException {
         String w = "";
    jj_consume_token(WORD);
      w = token.image;
      {if (true) return w;}
    throw new Error("Missing return statement in function");
  }

  final public void turn(String s) throws ParseException {
  if (s.equalsIgnoreCase("right")) {
   world.turnRight();

   }
   else if (s.equalsIgnoreCase("left")) {
     world.turnRight();
     world.turnRight();
     world.turnRight();
   }
  }

  final public void face(String s) throws ParseException {
     boolean b = false;
  if (s.equalsIgnoreCase("north")) {
    while(b == false) {
      if (world.facingNorth()) {

        b = true;

        }
     else {
          world.turnRight();
        }
     }

}
   else if (s.equalsIgnoreCase("south")) {
    while(b == false) {
      if (world.facingSouth()) {

        b = true;

        }
   else {
          world.turnRight();
        }
     }

}

else if (s.equalsIgnoreCase("east")) {
    while(b == false) {
      if (world.facingEast()) {

        b = true;

        }
   else {
          world.turnRight();
        }
     }

}

else if (s.equalsIgnoreCase("west")) {
    while(b ==false) {
      if (world.facingWest()) {

        b = true;

        }
   else {
          world.turnRight();
        }
     }

   }
  }

  final public void assign(String a ,int x) throws ParseException {
   variables.put(a,x);
  }

  final public void move(String a) throws ParseException {
 int x = 1;
  if(variables.containsKey(a)) {
   x = variables.get(a);
 }
world.moveForward(x);
  }

  final public void moveDir(int z, String dir) throws ParseException {
  String back = "";
    if(world.facingNorth()) {
      back = "North";
    }
    else if(world.facingSouth()) {
      back = "South";
    }
    else if(world.facingWest()) {
      back = "West)";
    }
    else if(world.facingEast()) {
      back = "East";
    }

        if(dir.equalsIgnoreCase("right")){
                if(world.facingEast()){
                world.moveHorizontally(z);
                }
                else {
                        int n= 0;
                        while(world.facingEast()== false){
                                world.turnRight();
                                n++;
                        }
                        world.moveHorizontally(z);
                        turn(back);
                }
        }
        else if(dir.equalsIgnoreCase("left")){
                if(world.facingWest()){
                        world.moveHorizontally(z);
                        }
                        else {
                                int n= 0;
                                while(world.facingWest() == false){
                                        world.turnRight();
                                        n++;
                                }
                                world.moveHorizontally(z);
                                turn(back);
                        }
        }
        else if(dir.equalsIgnoreCase("front")){
                if(world.facingEast() || world.facingWest()){
                        world.moveHorizontally(z);
                }
                else {
                        world.moveVertically(z);
                }
        }
        else {
                if(world.facingEast()){
                        int n= 0;
                        while(world.facingWest() == false){
                                world.turnRight();
                                n++;
                        }
                        world.moveHorizontally(z);
                        turn(back);
                }
                else if(world.facingWest()){
                        int n= 0;
                        while(world.facingEast()== false){
                                world.turnRight();
                                n++;
                        }
                        world.moveHorizontally(z);
                        turn(back);
                }
                else if (world.facingNorth()){
                        int n= 0;
                                while(world.facingSouth() == false){
                                        world.turnRight();
                                        n++;
                                }
                                world.moveVertically(z);;
                                turn(back);
                }
                else {
                        int n= 0;
                        while(world.facingNorth()== false){
                                world.turnRight();
                                n++;
                        }
                        world.moveVertically(z);;
                        turn(back);
                }
        }
  }

  final public boolean facing(String s) throws ParseException {
      boolean b = false;
             if (s.equals("north")) {
              b = world.facingNorth();

             }
             else if (s.equals("south")) {
              b = world.facingSouth();

             }
             else  if (s.equals("west")) {
              b = world.facingWest();

             }
             else if (s.equals("east")) {
              b = world.facingEast();

             }

              {if (true) return b;}
    throw new Error("Missing return statement in function");
  }

  final public void moveInDir(String x, String face) throws ParseException {
      int num = 0;
        face(face);
        num = variables.get(x);
        world.moveForward(num);
  }

  final public void comands(String sistem) throws ParseException {
     String a;
     String c;
     int x;
     boolean b;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case T_TURNRIGHT:
      jj_consume_token(T_TURNRIGHT);
      jj_consume_token(25);
      jj_consume_token(26);
      jj_consume_token(27);
                                          world.turnRight();
      break;
    case T_MOVER:
      jj_consume_token(T_MOVER);
      jj_consume_token(25);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MI:
        a = letter();
        break;
      case NUMERO:
        a = num();
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(26);
      jj_consume_token(27);
                                                                       move(a);
      break;
    case T_PONER:
      jj_consume_token(T_PONER);
      jj_consume_token(25);
      x = numero();
      jj_consume_token(28);
      a = word();
      jj_consume_token(26);
      jj_consume_token(27);
                                                                         objetoPoner(a,x);
      break;
    case T_RECOGER:
      jj_consume_token(T_RECOGER);
      jj_consume_token(25);
      x = numero();
      jj_consume_token(28);
      a = word();
      jj_consume_token(26);
      jj_consume_token(27);
                                                                                 objetoRecoger(a,x);
      break;
    case ASSIGN:
      jj_consume_token(ASSIGN);
      jj_consume_token(25);
      a = letter();
      jj_consume_token(28);
      x = numero();
      jj_consume_token(26);
      jj_consume_token(27);
                                                                         assign(a,x);
      break;
    case TURN:
      jj_consume_token(TURN);
      jj_consume_token(25);
      a = word();
      jj_consume_token(26);
      jj_consume_token(27);
                                                    turn(a);
      break;
    case FACE:
      jj_consume_token(FACE);
      jj_consume_token(25);
      a = word();
      jj_consume_token(26);
      jj_consume_token(27);
                                                    face(a);
      break;
    case MOVE_DIR:
      jj_consume_token(MOVE_DIR);
      jj_consume_token(25);
      x = numero();
      jj_consume_token(28);
      a = word();
      jj_consume_token(26);
      jj_consume_token(27);
                                                                         moveDir(x,a);
      break;
    case MOVE_IN_DIR:
      jj_consume_token(MOVE_IN_DIR);
      jj_consume_token(25);
      c = letter();
      jj_consume_token(28);
      a = word();
      jj_consume_token(26);
      jj_consume_token(27);
                                                                             moveInDir(c,a);
      break;
    case 33:
      not(sistem);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void options(String sistem) throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case T_MOVER:
      case T_TURNRIGHT:
      case T_PONER:
      case T_RECOGER:
      case ASSIGN:
      case TURN:
      case FACE:
      case MOVE_DIR:
      case MOVE_IN_DIR:
      case 29:
      case 31:
      case 33:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 29:
        corchete(sistem);
        break;
      case T_MOVER:
      case T_TURNRIGHT:
      case T_PONER:
      case T_RECOGER:
      case ASSIGN:
      case TURN:
      case FACE:
      case MOVE_DIR:
      case MOVE_IN_DIR:
      case 33:
        comands(sistem);
        break;
      case 31:
        cuadrado(sistem);
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void corchete(String sistem) throws ParseException {
     String a;
     String c;
     int x;
    jj_consume_token(29);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case T_MOVER:
      case T_TURNRIGHT:
      case T_PONER:
      case T_RECOGER:
      case ASSIGN:
      case TURN:
      case FACE:
      case MOVE_DIR:
      case MOVE_IN_DIR:
      case 31:
      case 33:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case T_MOVER:
      case T_TURNRIGHT:
      case T_PONER:
      case T_RECOGER:
      case ASSIGN:
      case TURN:
      case FACE:
      case MOVE_DIR:
      case MOVE_IN_DIR:
      case 33:
        comands(sistem);
        break;
      case 31:
        cuadrado(sistem);
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(30);
  }

  final public void cuadrado(String sistem) throws ParseException {
     String a;
     String c;
     int x;
    jj_consume_token(31);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case T_MOVER:
      case T_TURNRIGHT:
      case T_PONER:
      case T_RECOGER:
      case ASSIGN:
      case TURN:
      case FACE:
      case MOVE_DIR:
      case MOVE_IN_DIR:
      case 29:
      case 33:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case T_MOVER:
      case T_TURNRIGHT:
      case T_PONER:
      case T_RECOGER:
      case ASSIGN:
      case TURN:
      case FACE:
      case MOVE_DIR:
      case MOVE_IN_DIR:
      case 33:
        comands(sistem);
        break;
      case 29:
        corchete(sistem);
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(32);
  }

  final public void not(String sistem) throws ParseException {
  String a;
  boolean b;
    jj_consume_token(33);
    jj_consume_token(25);
    jj_consume_token(WORD);
    jj_consume_token(25);
    a = word();
    jj_consume_token(26);
    jj_consume_token(26);
    jj_consume_token(27);
    b = facing(a);

     if (b == false )
   sistem = "Not facing that direction";
  }

  /** Generated Token Manager. */
  public RobotTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[9];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x401,0x800020,0x1f3c0,0xa001f3c0,0xa001f3c0,0x8001f3c0,0x8001f3c0,0x2001f3c0,0x2001f3c0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x2,0x2,0x2,0x2,0x2,0x2,0x2,};
   }

  /** Constructor with InputStream. */
  public Robot(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Robot(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RobotTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Robot(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new RobotTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Robot(RobotTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(RobotTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[34];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 9; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 34; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
