/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MI = 5;
  /** RegularExpression Id. */
  int T_MOVER = 6;
  /** RegularExpression Id. */
  int T_TURNRIGHT = 7;
  /** RegularExpression Id. */
  int T_PONER = 8;
  /** RegularExpression Id. */
  int T_RECOGER = 9;
  /** RegularExpression Id. */
  int ROBOT = 10;
  /** RegularExpression Id. */
  int VARS = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int TURN = 13;
  /** RegularExpression Id. */
  int FACE = 14;
  /** RegularExpression Id. */
  int MOVE_DIR = 15;
  /** RegularExpression Id. */
  int MOVE_IN_DIR = 16;
  /** RegularExpression Id. */
  int WORD = 17;
  /** RegularExpression Id. */
  int T_BALLOONS = 18;
  /** RegularExpression Id. */
  int T_CHIPS = 19;
  /** RegularExpression Id. */
  int NUMERO = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<MI>",
    "\"move\"",
    "\"TURNRIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"ROBOT_R\"",
    "<VARS>",
    "\"assign\"",
    "\"turn\"",
    "\"face\"",
    "\"moveDir\"",
    "\"moveInDir\"",
    "<WORD>",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUMERO>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\" ;\"",
    "\" ,\"",
  };

}
